"""members: org_code, user profile + status + notify flags

Revision ID: 23a1d4dec2fe
Revises: 5e86b8044337
Create Date: 2026-06-04 19:41:46.285828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23a1d4dec2fe'
down_revision: Union[str, Sequence[str], None] = '5e86b8044337'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('org_code', sa.String(length=16), nullable=False))
    op.create_index(op.f('ix_tenants_org_code'), 'tenants', ['org_code'], unique=False)
    op.add_column('users', sa.Column('name', sa.String(length=120), nullable=False))
    op.add_column('users', sa.Column('phone', sa.String(length=32), nullable=False))
    op.add_column('users', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('email_enabled', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('sms_enabled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sms_enabled')
    op.drop_column('users', 'email_enabled')
    op.drop_column('users', 'status')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'name')
    op.drop_index(op.f('ix_tenants_org_code'), table_name='tenants')
    op.drop_column('tenants', 'org_code')
    # ### end Alembic commands ###
