"""initial schema

Revision ID: 5e86b8044337
Revises: 
Create Date: 2026-06-04 05:24:57.391427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e86b8044337'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_resets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('otp_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.Float(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_resets_email'), 'password_resets', ['email'], unique=False)
    op.create_table('singleton_leases',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('holder', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('tenants',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('alert_emails', sa.String(length=2000), nullable=False),
    sa.Column('alert_phones', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('eui', sa.String(length=32), nullable=False),
    sa.Column('location', sa.String(length=300), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('opened_at', sa.Float(), nullable=False),
    sa.Column('cleared_at', sa.Float(), nullable=False),
    sa.Column('last_notified_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alert_open', 'alerts', ['tenant_id', 'eui', 'kind', 'state'], unique=False)
    op.create_index(op.f('ix_alerts_eui'), 'alerts', ['eui'], unique=False)
    op.create_index(op.f('ix_alerts_tenant_id'), 'alerts', ['tenant_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('last_used_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_tenant_id'), 'api_keys', ['tenant_id'], unique=False)
    op.create_table('readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('ts', sa.Float(), nullable=False),
    sa.Column('eui', sa.String(length=32), nullable=False),
    sa.Column('box', sa.Integer(), nullable=False),
    sa.Column('slot', sa.String(length=2), nullable=False),
    sa.Column('probes', sa.Text(), nullable=False),
    sa.Column('max_c', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reading_tenant_ts', 'readings', ['tenant_id', 'ts'], unique=False)
    op.create_index(op.f('ix_readings_eui'), 'readings', ['eui'], unique=False)
    op.create_index(op.f('ix_readings_tenant_id'), 'readings', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_readings_ts'), 'readings', ['ts'], unique=False)
    op.create_table('sensor_map',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('eui', sa.String(length=32), nullable=False),
    sa.Column('box', sa.Integer(), nullable=False),
    sa.Column('slot', sa.String(length=2), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('rack_id', sa.String(length=64), nullable=False),
    sa.Column('unit_id', sa.String(length=64), nullable=False),
    sa.Column('port_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_map_eui'), 'sensor_map', ['eui'], unique=False)
    op.create_index(op.f('ix_sensor_map_tenant_id'), 'sensor_map', ['tenant_id'], unique=False)
    op.create_index('ix_sensormap_tenant_eui', 'sensor_map', ['tenant_id', 'eui'], unique=True)
    op.create_table('thresholds',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.Column('scope_id', sa.String(length=64), nullable=False),
    sa.Column('high_c', sa.Float(), nullable=False),
    sa.Column('delta_c', sa.Float(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_threshold_scope', 'thresholds', ['tenant_id', 'scope', 'scope_id'], unique=True)
    op.create_index(op.f('ix_thresholds_tenant_id'), 'thresholds', ['tenant_id'], unique=False)
    op.create_table('topologies',
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('json', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('topologies')
    op.drop_index(op.f('ix_thresholds_tenant_id'), table_name='thresholds')
    op.drop_index('ix_threshold_scope', table_name='thresholds')
    op.drop_table('thresholds')
    op.drop_index('ix_sensormap_tenant_eui', table_name='sensor_map')
    op.drop_index(op.f('ix_sensor_map_tenant_id'), table_name='sensor_map')
    op.drop_index(op.f('ix_sensor_map_eui'), table_name='sensor_map')
    op.drop_table('sensor_map')
    op.drop_index(op.f('ix_readings_ts'), table_name='readings')
    op.drop_index(op.f('ix_readings_tenant_id'), table_name='readings')
    op.drop_index(op.f('ix_readings_eui'), table_name='readings')
    op.drop_index('ix_reading_tenant_ts', table_name='readings')
    op.drop_table('readings')
    op.drop_index(op.f('ix_api_keys_tenant_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_alerts_tenant_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_eui'), table_name='alerts')
    op.drop_index('ix_alert_open', table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('tenants')
    op.drop_table('singleton_leases')
    op.drop_index(op.f('ix_password_resets_email'), table_name='password_resets')
    op.drop_table('password_resets')
    # ### end Alembic commands ###
